<a href="https://colab.research.google.com/github/2018130864-KwonHaYeon/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

phasor(amp, sr, dur, freq)


return s, theta, t

In [15]:
def phasor(amp, sr, dur, freq):
  t = np.arange(1, sr*dur + 1)/sr
  theta = t*2*np.pi*freq
  s = np.sin(theta)
  return s, theta, t

In [16]:
phasor(1, 10000, 1, 100.0)

(array([ 6.27905195e-02,  1.25333234e-01,  1.87381315e-01, ...,
        -1.25333234e-01, -6.27905195e-02,  3.92877345e-15]),
 array([6.28318531e-02, 1.25663706e-01, 1.88495559e-01, ...,
        6.28192867e+02, 6.28255699e+02, 6.28318531e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 9.998e-01, 9.999e-01,
        1.000e+00]))

In [17]:
def phasor_audio(amp, sr, dur, freq):
  t = np.arange(1, sr*dur + 1)/sr
  theta = t*2*np.pi*freq
  s = np.sin(theta)
  return ipd.Audio(s, rate=sr)

In [19]:
phasor_audio(1, 10000, 1, 100.0)